communication/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^chat-message/(?P<article_id>[0-9]+)/$', views.chat_message, name="chat_message"),
    re_path(r'^box_message/', views.box_msg, name="box_msg"),
    re_path(r'^notifications/', views.notifications, name="notifications"),
    re_path(r'^redirect-from-notif/', views.notif_detail, name="notif_redirect"),
]

app_name = "communication"

dashboard/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    # re_path(r'^$', views.my_articles, name='my_articles'),
    # re_path(r'^delete/', views.delete_article, name='delete'),
    # re_path(r'^selled_list/$', views.selled_article_list, name='selled_list'),
    # re_path(r'^bought_list/$', views.bought_article_list, name='bought_list'),
    #ajout provisoire de url
    re_path(r'^factures/[a-z.ç]*', views.invoices, name="invoices"),
    re_path(r'^commandes/[a-zç]*$', views.orders, name="orders"),
    re_path(r'^payement/', views.payement, name="payement"),
    re_path(r'^achats-en-attentes/$', views.transactions, name="waiting-buy"),
    re_path(r'^ventes-en-attentes/$', views.transactions, name="waiting-sell"),
    re_path(r'^achats-effectués/$', views.transactions, name="articles-bought"),
    re_path(r'^ventes-réalisées/$', views.transactions, name="articles-selled"),
    re_path(r'^annuler-achat/$', views.transactions, name="cancel-transaction"),
]

app_name = 'dashboard'

store/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
    re_path(r'^supprimer-un-article/(?P<article_id>[0-9]+)/$', views.delete_article, name='delete'),
    re_path(r'^poster-un-article/', views.create_article, name="create_article"),
    re_path(r'^modifier-article/(?P<article_id>[0-9]+)/$', views.update, name='update'),
    re_path(r'^mes-favoris/$', views.favourite, name="favourite"),
    re_path(r'^mes-articles-ajoutés/$', views.my_articles_added, name="my_articles"),
    re_path(r'^rechercher-un-article/', views.search, name="search"),
]

app_name = 'store'

user/urls.py
from django.urls import re_path

from user import views

urlpatterns = [
    re_path(r'^login/', views.login_user, name="login"),
    re_path(r'^register/', views.register, name="register"),
    re_path(r'^auto_login/', views.auto_login, name="auto_login"),
    re_path(r'^profil/', views.profil, name="profil"),
    re_path(r'^security/', views.security, name="security"),
    re_path(r'^logout/', views.logout_user, name='logout'),
]

app_name = 'user'

store/forms.py
from django import forms

from store.models import Article

class ArticleForms(forms.ModelForm):
    class Meta:
        ATTRS_DATA = {"class": "form-control border-0 border-bottom border-secondary"}
        model = Article
        fields = ('name', 'description', 'price_init', 'number', 
                'town', 'district', 'status', 'image_min', 'category'
                , 'delivery')
        widgets = {
            'name': forms.TextInput(attrs=ATTRS_DATA),
            'description': forms.Textarea(attrs={"class": "form-control", "rows": "4"}),
            'price_init': forms.NumberInput(attrs=ATTRS_DATA),
            'number': forms.NumberInput(attrs=ATTRS_DATA),
            'town': forms.Select(attrs=ATTRS_DATA),
            'district': forms.TextInput(attrs=ATTRS_DATA),
            'status': forms.Select(attrs=ATTRS_DATA),
            'image_min': forms.FileInput(attrs=ATTRS_DATA),
            'category': forms.Select(attrs=ATTRS_DATA),
            'delivery': forms.CheckboxInput(attrs={"class": "w-50 h-50"}),
        }

store/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.db.models import Q, F
from django.views.decorators.cache import cache_page
from django.core.paginator import Paginator, EmptyPage
from django.contrib import messages
from PIL import Image
import os
import logging as lg
from spectreCorp.settings import BASE_DIR
from django.core.files import File

from .models import Article, Picture, Category, Favourite
from dashboard.models import Order
from communication.models import NotifMessage
from .utils import *
from .forms import ArticleForms
 
def home(request):
    articles = Article.objects.filter(available=True).order_by('-date_add')
    
    #articles in cachearticle_add_in_favourite_success
    if not cache.get('articles_home'):
        cache.set('articles_home', articles)
    
    articles = cache.get('articles_home')
        
    paginator = Paginator(articles, 10)
    try:
        page = request.GET.get('page')
        articles = paginator.page(page)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    except:
        articles = paginator.page(1)
        
    context = {
        'white_font': True, 
        'articles': articles,
    }
    
    #verify if user is new comer to send welcome message
    try:
        request.user
        send_welcome_message_to_new_user(request.user, NotifMessage, User)
    except:
        pass
    
    return render(request, 'store/index.html', context)

def detail(request, article_id):
    #filtre seller of article_id to get list of all article from this seller
    article = get_object_or_404(Article, id=article_id)
    seller_id = article.user.id
    
    #set of cache request on database
    articles_category_cache_name = f'filter_{article.category}'
    if not cache.get(articles_category_cache_name):
        cache.set(articles_category_cache_name, Article.objects.filter(available=True, \
            category=article.category).order_by('-date_add'))
    
    articles_user_cache_name = f'{article.user}_articles'
    if not cache.get(articles_user_cache_name):
        cache.set(articles_user_cache_name, Article.objects.filter(Q(user__id=seller_id) & \
            Q(available=True)))
    
    #get articles with same category with article select
    articles_same_category = cache.get(articles_category_cache_name)
    
    articles_for_seller = cache.get(articles_user_cache_name)
    
    context = {
        'articles': articles_same_category,
        'articles_for_seller': articles_for_seller,
        'article': article,
        'pictures': article.pictures.all(),
    }
    
    try:
        request.user
        context['favourite_articles'] = Article.objects.filter(favourite__user=request.user) 
    except:
        pass
    
    #add 1 to seen article
    article.seen += 1
    article.save()
    return render(request, 'store/detail.html', context)

def search(request):
    if request.GET:
        category = request.GET.get('category')
        query = request.GET.get('query')
        word_to_search = None
        
        if query != "":
            if category == 'all':
                word_to_search = f"{query} categorie: tout"
                #cache don't accept space for his key we remove any space
                cache_name = "".join(f"filter_{query}".split(" "))
                articles = get_or_create_cache(cache_name, Article, Q(name__icontains=query)\
                    & Q(available=True))
            else:
                category = get_object_or_404(Category, name=category)
                cache_name = "".join(f"filter_{category}_{query}".split(" "))
                articles = get_or_create_cache(cache_name, Article, Q(name__icontains=query) \
                    & Q(category=category) & Q(available=True))
                word_to_search = f"{query} categorie: {category}"
        elif category == "all":
            articles = get_or_create_cache("all", Article)
            word_to_search = "Toutes catégories"
        else:
            category = get_object_or_404(Category, name=category)
            articles = get_or_create_cache(f"filter_{category}", Article, Q(category=category))
            word_to_search = category
            
        context = {
            'articles': articles,
            'elt_to_search': word_to_search,
        }
        
        return render(request, 'store/search_result.html', context)

@login_required
def create_article(request):
    form = ArticleForms(None)
    if request.POST:
        form = ArticleForms(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.back_color = get_dominate_color(article.image_min)
            try:
                article.save()
                messages.add_message(request, messages.SUCCESS, article_save_success(article))
            except Exception as e:
                print("Not save ", e)
            else: 
                image_min_for_article = 1 #number of image direct in article
                image_sup_count = len(request.FILES) - image_min_for_article
                if image_sup_count > 0:
                    for i in range(1, image_sup_count + 1):
                        img = request.FILES.get(f"image_{i}")
                        try:
                            Picture.objects.create(photo=img, article=article)
                        except Exception as e:
                            lg.debug(f"Not save {e}")
                cache.delete('articles_home')#clear articles list in home
                return redirect('store:my_articles')

    context = {
        'form': form
    }
    return render(request, 'store/create.html', context)

@login_required
def update(request, article_id):
    id = int(article_id)
    article = get_object_or_404(Article, id=id)
    form = ArticleForms(instance=article)
    if request.POST:
        form = ArticleForms(request.POST, request.FILES, instance=article)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user          
            article.save()
            messages.success(request, article_update_success(article))
            #clear cache set in my_articles views
            cache.delete_many([f'available_articles_{request.user.id}', \
                f'unavailable_articles_{request.user.id}'])
            cache.delete('articles_home')#clear articles list in home
            return redirect('store:my_articles')   
    
    #deactivate/activate article
    if request.GET.get("availability"):
        #clear cache for home page
        cache.delete("articles_home")
        availability = request.GET.get("availability")
        if availability == "available": 
            article.available = True
            article.save()
            #clear cache
            cache.delete(f"unavailable_articles_{request.user.id}")
        elif availability == "unavailable":
            article.available = False
            article.save()
            #clear cache
            cache.delete(f"available_articles_{request.user.id}")
        
        return redirect('store:my_articles')
            
    context = {
        'article': article,
        'form': form,
        'categories': Category.objects.all(),
    }

    return render(request, 'store/update.html', context)

@login_required
def favourite(request):
    VIEW_PATH = '/store/mes-favoris/'
    cache_name = f"articles_favourite_{request.user}"
    
    if request.GET.get('article_id'):
        article_id = request.GET.get('article_id')
        article = get_object_or_404(Article, pk=article_id)
        try:
            favourite = get_object_or_404(Favourite, user=request.user)
        except Exception as e:
            favourite = Favourite.objects.create(user=request.user)
        #verify if article is in favourite
        if article in favourite.articles.all():
            messages.info(request, article_add_in_favourite_if_exist(article))
        else:
            favourite.articles.add(article)
            messages.success(request, article_add_in_favourite_success(article))
            #clear cache
            cache.delete(cache_name)
            
    elif request.GET.get('delete_article_id'):
        article_id = request.GET.get('delete_article_id')
        article = get_object_or_404(Article, pk=article_id)
        favourite = get_object_or_404(Favourite, user=request.user)
        favourite.articles.remove(article)
        #clear cache
        cache.delete(cache_name)
    
    if not cache.get(cache_name):
        try:
            articles_favourite = Favourite.objects.get(user=request.user).articles.all()
        except Exception:
            articles_favourite = Favourite.objects.create(user=request.user).articles.all()
        cache.set(cache_name, articles_favourite)
        
    context = {
        'articles': cache.get(cache_name),
        'favourite_page': True,
        'view_path': VIEW_PATH,
    }
    return render(request, 'store/favourite.html', context)

@login_required
def my_articles_added(request):
    def get_article(availability=True):
        return Article.objects.filter(Q(user=request.user) & \
            Q(available=availability))
    
    available_cache_name = f'available_articles_{request.user.id}'
    unavailable_cache_name = f'unavailable_articles_{request.user.id}'
    if not cache.get(available_cache_name) or not cache.get(unavailable_cache_name):        
        cache.set(available_cache_name, get_article(True))
        cache.set(unavailable_cache_name, get_article(False))
    
    context ={
        'articles_available_of_seller': cache.get(available_cache_name),
        'articles_unavailable_of_seller': cache.get(unavailable_cache_name),
    }

store/templates/store/article_forms.html
<div class="row rowBloc2">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <label for="">Titre ou nom de l'article</label>
            </div>
            <div class="col-md-6">
                {{ form.name }}
            </div>
        </div>
        
        <hr>

        <div class="row">
            <div class="col-md-6">
                <label for="">Décrivez votre article</label>
            </div>
            <div class="col-md-6">
                {{ form.description }}
            </div>
        </div>
    </div>
</div>

<div class="row rowBloc3">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <label for="">Catégorie</label>
            </div>
            <div class="col-md-6">
                {{ form.category }}
            </div>
        </div>

        <hr>

    </div>

    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <label for="">Etat</label>
            </div>
            <div class="col-md-6">
                {{ form.status }}
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <hr>
        <div class="row">
            <div class="col-md-6">
                <label for="">Nombre d'article(s)</label>
            </div>
            <div class="col-md-6">
                {{ form.number }}
            </div>
        </div>
    </div>
</div>

<div class="row rowBloc5">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <label for="">Prix xaf</label>
            </div>
            <div class="col-md-6">
                {{ form.price_init }}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <label for="">Ville</label>
            </div>
            <div class="col-md-6">
                {{ form.town }}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <label for="">Quartier</label>
            </div>
            <div class="col-md-6">
                {{ form.district }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                <label for="">Livraison</label>
            </div>
            <div class="col-6">
                {{ form.delivery }}
            </div>
        </div>

        <hr>
        <div class="row">
            <div class="col-md-6">
                <label for="">Photo principale de l'article</label>
            </div>
            <div class="col-md-6">
                {{ form.image_min }}
            </div>
        </div>
        
        <hr>
        {% if request.path == "/store/poster-un-article/" %}
            <div class="row rowBloc1">
                <div class="col-12">
                    <label for="">Vous pouvez ajouter des photos supplémentaires ici</label> <br>
                    <div class="bloc-flex">
                        <div class="row upload_pics">

                        </div>
                        <div class="row btn-list">
                            <div class="col-12 text-center">
                                <button class="add-pics-btn">Choisir une photo</button><br>
                                <span class="alert"></span>
                                <input type="number" id="count_click" name="count_click" hidden="hidden">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

    </div>
</div>
<div class="row rowBloc4 text-right">
    <div><button type="submit">Sauvegarder</button></div>
    <div><a href="{% url 'store:my_articles' %}">Annuler</a></div>
</div>

store/templates/store/create.html
{% extends 'base.html' %}
{% block content %}
    <div class="body-page-content container">
        <div class="row">
            <h1>Vends ton article</h1>
        </div>
        <form action="{% url 'store:create_article' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'store/form.html' %}
        </form>
    </div>
{% endblock %}

store/templates/store/detail.html
{% extends 'base.html' %}
{% load static humanize %}
{% block content %}
<div class="body-page-content container-fluid p-3 bg-secondary">
  <div class="row bg-secondary">
    <div class="bg-secondary col-12 col-md-8 p-2 mb-2">
      <figure class="figure w-100 text-center bg-light h-100 rounded-2">
        <figcaption class="figure-caption text-center font-md">{{ article.name }}</figcaption>
        <img src="{{ article.image_min.url }}" id="figure-img-principal" class="figure-img img-fluid rounded" alt="{{ article }}">
        <div class="img-sup d-flex justify-content-center rounded-1 overflow-hidden">
          {% for picture in article.pictures.all %}
            {% if picture.photo %}
              <img src="{{ picture.photo.url }}" class="img-sup-item pointer {% if forloop.first %}border-2{% endif %}" alt="{{ article }}">
            {% endif %}
          {% empty %}
            <p>Aucune image suplémentaire</p>
          {% endfor %}
        </div>
      </figure>
    </div>
    
    <div class="col-12 bg-secondary p-2 col-md-4 mb-2">
      <aside class="aside-details">
        <div class="card">
          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between">
              <span class="d-block text-secondary">Prix</span><span class="d-block font-weight-bold">{{ article.price_ttc|intcomma }} XAF</span>
            </li>
            <li class="list-group-item d-flex justify-content-between text-secondary">
                <span class="d-block">Ville</span><span class="d-block">{{ article.town }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between text-secondary">
                <span class="d-block">Quartier</span> <span class="d-block">{{ article.district }}</span>
            </li>
            <li class="list-group-item text-secondary">
                <h5 class="d-block">Description</h5>  
                <p class="d-block">{{ article.description }}</p>
            </li>
            <li class="list-group-item d-flex justify-content-between text-secondary">
                <span class="d-block">Etat</span><span class="d-block">{{ article.status }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between text-secondary">
              <span class="d-block">Posté</span><span class="d-block">{{ article.date_add|naturaltime }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between text-secondary">
                <span class="d-block">Consulté</span><span class="d-block">{{ article.seen }} fois</span>
            </li>
            <li class="list-group-item d-flex justify-content-between text-secondary">
              <span class="d-block">Livraison</span><span class="d-block">{{ article.delivery }}</span>
            </li>
            {% if request.user != article.user %}
            <li class="list-group-item d-flex flex-column">
              <a href="{% url 'communication:chat_message' article_id=article.id %}" type="button" class="btn btn-outline-secondary text-primary">Envoyer un message</a>
              {# if article number is equal to 0, we can not pass an order #}
              {% if article.number > 0 %}
                <a href="{% url 'dashboard:orders' %}?article_id={{ article.id }}" type="button" class="btn btn-primary mt-2 mb-2 dialog_confirm_before">
                  Passer la commande <span class="d-none">Envoie d'une commande pour l'article {{ article }}</span>
                </a>
              {% else %}
                <button class="btn btn-outline-dark" disabled>Cet article est déjà en cours de commande</button>
              {% endif %}
              <a href="{% url 'store:favourite' %}?article_id={{ article.id }}" type="button" class="btn btn-outline-secondary text-primary">Ajouter aux favoris</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </aside>    
    </div>
  </div>

  <div class="row p-2">
    <h5 class="alert alert-primary text-center">Articles similaires</h5>
    {% include 'store/list.html' with empty_article_text_alert="Aucun article similaire trouvé" %}
  </div>

</div>
{% endblock %}

store/templates/store/favourite.html
{% extends 'base.html' %}
{% block content %}
<div class="body-page-content container-fluid">
    <div class="row">
        <p class="col-12 text-xl-center alert alert-primary font-weight-bold" role="alert">
            Mes favoris
        </p>
    </div>
    <div class="container">
        {% include 'store/list.html' with empty_article_text_alert="Aucun article disponible ajouté aux favoris" %}
    </div>
</div>
{% endblock %}

store/templates/store/index.html
{% extends 'base.html' %}
{% block content %}
{% load cache %}
<div class="body-page-content">
    <div class="jumbotron-caroussel bg-secondary">
      <div class="jumbotron jumbotron-fluid">
        <div class="container shadow-lg">
          <h1 class="display-4 font-md">Rendez-vous la vie facile !</h1>
          <p class="lead font-sm-sm font-md">
            SC vous facilite la vie en achetant vos articles en ligne <br>
            et en toute sécurité !
          </p>
        </div>
        <img src="../static/images/pictures/pic1.png" hidden alt="">
        <span class="background-color d-none">#1a4422</span>
      </div>

      <div class="jumbotron jumbotron-fluid">
        <div class="container shadow-lg">
          <h1 class="display-4 font-md ">MTN mobile money <br> et Airtel money</h1>
          <p class="lead font-sm-sm">
            Achetez vos articles en utilisant <br>
            votre compte électronique mobile
          </p>
        </div>
        <img src="../static/images/pictures/b1.jpg" hidden alt="">
      </div>

      <div class="jumbotron jumbotron-fluid">
        <div class="container shadow-lg">
          <h1 class="display-4 font-md">Fluid  3</h1>
          <p class="lead font-sm-sm">This is a modified jumbotron th</p>
        </div>
        <img src="../static/images/pictures/pic4.jpg"   hidden alt="">
      </div>

    </div>

    <div class="d-md-none d-flex flex-column align-items-center pt-4 bloc_btn">
      <a href="{% url 'store:create_article' %}" class="btn-style w-100 mb-3" style="text-decoration: none;"> Poster un article à vendre</a></a>
      <p><a href="{% url 'work_step' %}" class="text-primary">Comment ça marche ?</a></p>
    </div>
    <!--============including articles list html ====================-->
    {% include 'store/list.html' %}
</div>

{% endblock %}

store/templates/store/list.html
{% load humanize static %}
<div class="articles row row-cols-2 row-cols-md-3 row-cols-xl-4 mt-md-3 p-1 justify-content-around">
    {% for article in articles %}
    <div class="article p-1 col">
      <div class="card p-0">
      <a href="{% url 'store:detail' article_id=article.id %}" style="background: rgb{{ article.back_color }}">
          <div class="background-img w-100" style="background: url({{ article.image_min.url }}) no-repeat center center;
          background-size: contain">
          </div>
        </a>
        <div class="card-body p-1 pb-0">
          <h5 class="card-title text-secondary font-md mb-0 text-truncate">{{ article.name }} <br></h5>
          <span class="d-block mt-0 font-sm-esm text-truncate">{{ article.date_add|naturaltime }}</span>
        </div>

        <ul class="list-group list-group-flush">
        {% if request.user.is_authenticated and request.path == "/store/mes-articles-ajoutés/" %}
            <li class="list-group-item p-0 d-flex justify-content-between text-secondary font-sm-sm">
              <span class="d-block font-sm-sm ">Prix:</span> 
              {% if article.price_init >= 1000000 %} 
                <span class="d-block text-dark text-truncate">{{ article.price_init|intword }} XAF</span>
              {% else %}
                <span class="d-block text-dark text-truncate">{{ article.price_init|intcomma }} XAF</span>
              {% endif %}
            </li>
            <li class="list-group-item p-0 d-flex flex-wrap justify-content-between text-light font-sm-sm">
              <a href="{% url 'store:delete' article_id=article.id %}" class="d-block btn btn-danger text-light p-0 flex-fill dialog_confirm_before" >
                supprimer <span class="title_confirm_for_js d-none" >Suppresion de l'article {{ article.name }}</span>
              </a> 
              <a href="{% url 'store:update' article_id=article.id %}" class="d-block btn btn-info text-light p-0 flex-fill" >Modifier</a>
            </li>
            <li class="list-group-item p-0 d-flex flew-wrap justify-content-between text-light font-sm-sm">
              {% if article.available %}
                <button type="button" class="btn btn-secondary flex-fill p-0 font-sm-sm" disabled>Activé</button>              
                <a href="{% url 'store:update' article_id=article.id %}?availability=unavailable" type="button" class="btn btn-outline-secondary flex-fill p-0 font-sm-sm">Désactivé ?</a> 
              {% else %}
                <a href="{% url 'store:update' article_id=article.id %}?availability=available" type="button" class="btn btn-outline-secondary flex-fill p-0 font-sm-sm" >Activé ?</a>              
                <button disabled type="button" class="btn btn-secondary flex-fill p-0 font-sm-sm">Désactivé</button> 
              {% endif %}
            </li>
        {% else %}
          <ul class="list-group list-group-flush">
            <li class="list-group-item p-0 d-flex justify-content-between text-secondary font-sm-sm">
              <span class="d-block font-sm-sm ">Prix:</span> 
              {% if article.price_ttc >= 1000000 %} 
                <span class="d-block text-dark text-truncate">{{ article.price_ttc|intword }} XAF</span>
              {% else %}
                <span class="d-block text-dark text-truncate">{{ article.price_ttc|intcomma }} XAF</span>
              {% endif %}
            </li>
            <li class="list-group-item p-0 d-flex justify-content-between text-secondary font-sm-sm">
              <span class="d-block"><img src="{% static 'images/icons/geo.png' %}" class="w-50" alt=""></span>  
              <span class="d-block text-truncate">{{ article.town }}</span>
            </li>
            {% if request.path == view_path %}
              <li class="list-group-item p-0 d-flex justify-content-between text-secondary font-sm-sm">
                <a href="{% url 'store:favourite' %}?delete_article_id={{ article.id }}" 
                class="btn text-primary w-100 text-center">Retirer</a>
              </li>
            {% endif %}
        {% endif %}
          <!--Views deactivate for now  
            <li class="list-group-item p-0 d-flex justify-content-between text-secondary font-sm-sm">
            <span class="d-block"><img src="{% static 'images/icons/eye.png' %}" class="w-50 w-sm-25" alt=""> 150</span>
          </li> -->
        </ul>

        <a href="{% url 'store:detail' article_id=article.id %}" class="btn-style text-light ">Consulter ?</a>
      </div>
    </div>
    {% empty %}
      <div class="alert alert-info w-50 text-center m-auto" role="alert">
        {{ empty_article_text_alert }}
      </div>
    {% endfor %}
</div>

store/templates/store/my_articles.html
{% extends 'base.html' %}
{% block content %}
<div class="body-page-content container-fluid">
    <div class="row">
        <h1 class="col-12 text-center bg-secondary font-weight-bold font-sm-md" >
            Mes articles ajoutés
        </h1>
    </div>
    <div class="p-0 row">
        {% include 'store/list.html' with articles=articles_available_of_seller empty_article_text_alert="Aucun article disponible" %}
    </div>
    
    {% if articles_unavailable_of_seller|length >= 1 %}
        <div class="row">
            <h2 class="bg-secondary text-center text-light w-100">
                Article{{ articles_unavailable_of_seller|pluralize }} non disponible{{ articles_unavailable_of_seller|pluralize }}
            </h2>
        </div>
        <div class="container">
            {% comment %}  
                no need to sepcify ampty_article_text_alert, coz this part is showing 
                only if articles_unavailable_of_seller is more than 0 
            {% endcomment %}
            {% include 'store/list.html' with articles=articles_unavailable_of_seller %}
        </div>
    {% endif %}    
</div>
{% endblock %}

store/templates/store/search_result.html
{% extends 'base.html' %}
{% block content %}
    <div class="body-page-content container-fluid">
        <div class="row">
            <p class="col-12 text-xl-center alert alert-primary font-weight-bold" role="alert">Resulat de recherche "{{ elt_to_search }}"</p>
        </div>
        <div class="container">
            {% include 'store/list.html' %}
        </div>
    </div>
{% endblock %}

store/templates/store/sell.html
{% extends 'base.html' %}
{% block content %}
    <div class="body-page-content container">
        <div class="row">
            <h1>Vends ton article</h1>
        </div>
        <form action="{% url 'store:create_article' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'store/form.html' %}
        </form>
    </div>
{% endblock %}

store/templates/store/update.html
{% extends 'base.html' %}
{% block content %}
<div class="body-page-content container">
    <form action="{% url 'store:update' article_id=article.id %}" method="post" 
    enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'store/form.html' %}
    </form>
</div>
{% endblock %}