store/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
    re_path(r'^supprimer-un-article/(?P<article_id>[0-9]+)/$', views.delete_article, name='delete'),
    re_path(r'^poster-un-article/', views.create_article, name="create_article"),
    re_path(r'^modifier-article/(?P<article_id>[0-9]+)/$', views.update, name='update'),
    re_path(r'^mes-favoris/$', views.favourite, name="favourite"),
    re_path(r'^mes-articles-ajoutés/$', views.my_articles_added, name="my_articles"),
    re_path(r'^rechercher-un-article/', views.search, name="search"),
]

app_name = 'store'

user/urls.py
from django.urls import re_path

from user import views

urlpatterns = [
    re_path(r'^login/', views.login_user, name="login"),
    re_path(r'^register/', views.register, name="register"),
    re_path(r'^auto_login/', views.auto_login, name="auto_login"),
    re_path(r'^profil/', views.profil, name="profil"),
    re_path(r'^security/', views.security, name="security"),
    re_path(r'^logout/', views.logout_user, name='logout'),
]

app_name = 'user'

user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

from store.utils import edit_image_before_save

class Gender(models.Model):
    sexe = models.CharField(max_length=15)
    
    def __str__(self):
        return self.sexe

class Profil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    gender = models.ForeignKey(Gender, on_delete=models.SET_NULL, null=True)
    contact_mtn = models.CharField(null=True, max_length=20, default="", blank=True)
    contact_airtel = models.CharField(null=True, max_length=20, default="", blank=True)
    whatsap_number = models.CharField(null=True, max_length=20, default="", blank=True)
    airtel_money = models.CharField(null=True, max_length=20, default="", blank=True)
    mtn_money = models.CharField(null=True, max_length=20, default="", blank=True)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            img = Image.open(self.avatar.path)
        except Exception as e:
            print(e)
        else:
            edit_image_before_save(self.avatar.path, 400)

user/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profil

class RegisterForm(forms.Form):
    username = forms.CharField(label="", max_length=100)
    email = forms.EmailField(label="")
    password = forms.CharField(label="", widget=forms.PasswordInput)
    confirm_password = forms.CharField(label="", widget=forms.PasswordInput)
    
    username.widget.attrs.update({'placeholder': 'Nom d\'utilisateur',
                                  'class': "w-100 border-bottom border-0"})
    email.widget.attrs.update({'placeholder': 'Email', 
                               'class': "w-100 border-bottom border-0"})
    password.widget.attrs.update({'placeholder': 'Mot de passe', 
                                'class': 'inputForm w-100 border-bottom border-0'})
    confirm_password.widget.attrs.update({'placeholder': 'Confirmer mot de passe', 
                                'class': 'inputForm w-100 border-bottom border-0'})
    
    def clean_confirm_password(self):
        confirm_password = self.cleaned_data['confirm_password']
        
        if confirm_password != self.cleaned_data['password']:
            raise forms.ValidationError('Les mots de passes diffèrent !')
        
        return confirm_password
    
    def clean_email(self):
        email = self.cleaned_data['email']
        
        try:
            User.objects.get(email=email)
        except:
            forms.ValidationError("Cet email existe déjà, vous connectez")
        
        return email
           
class LoginForm(forms.Form):
    username = forms.CharField(label="")
    password = forms.CharField(label="", widget=forms.PasswordInput)
    
    username.widget.attrs.update({'placeholder': 'Nom d\'utilisateur',
                                  "class": "w-100 border-bottom border-0"})
    password.widget.attrs.update({'placeholder': 'Mot de passe', 
                        'class': 'inputForm w-100 border-bottom border-0'})
             
class ProfilForm(forms.ModelForm):
    class Meta:
        fields = ('avatar', 'contact_mtn', 'contact_airtel', 'whatsap_number', 
                  'airtel_money', 'mtn_money', 'gender')
        model = Profil
        

class UserForm(forms.ModelForm):
    class Meta:
        fields = ('username', 'first_name', 'last_name', 'email')
        model = User

user/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import logout, authenticate, login, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView
from django.contrib import messages

from .forms import LoginForm, RegisterForm, ProfilForm, UserForm
from store.views import home
from .models import Profil, Gender
from communication.models import Message
from dashboard.models import Transaction

def login_user(request):
    """Login user"""
    #if user login, no need to see login view
    if request.user.is_authenticated:
        return redirect('store:home')
    form = LoginForm(request.POST or None)
    error = False
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                messages.add_message(request, messages.INFO, f'Content de vous voir {request.user} :)')
                return redirect('store:home')
            else:
                error = True
                content = 'ATTENTION ! Mot de passe ou nom d\'utilisateur invalide'
                messages.add_message(request, messages.ERROR, content)
    white_font = True    
    
    return render(request, 'user/login.html', locals())
        

def register(request):
    """Register new user"""
    #if user login, no need to see login view
    if request.user.is_authenticated:
        return redirect('store:home')
    form = RegisterForm(request.POST or None)
    email_exist = False
    username_exist = False 
    if form.is_valid():
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        check_email = User.objects.filter(email=email)
        check_username = User.objects.filter(username=username)
        if not check_email and not check_username:
            try:
                new_user = User.objects.create_user(username, email, password)
                user = User.objects.get(username=username)
                user_check = authenticate(username=user.username, password=password)
                login(request, user_check,  backend='django.contrib.auth.backends.ModelBackend')
            except Exception as e:
                print(e)
            else:
                messages.add_message(request, messages.SUCCESS, 'Votre compte a bien été crée !')
            
            return redirect('store:home')
        elif check_email:
            email_exist = True
        elif check_username:
            username_exist = True
    white_font = True
    
    return render(request, 'user/register.html', locals())

def auto_login(request):
    if request.user.is_authenticated:
        return redirect('store:home')
    return render(request, 'user/auto_login.html', {})

@login_required
def profil(request):
    password_update_page = False
    user_instance = User.objects.get(pk=request.user.id)
    profil_instance, created = Profil.objects.get_or_create(user=request.user)
    
    user_form = UserForm(instance=user_instance)
    profil_form = ProfilForm(instance=profil_instance)
    
    if request.POST:
        user_form = UserForm(request.POST, instance=user_instance)
        if user_form.is_valid():
            user_form.save()

        profil_form = ProfilForm(request.POST, request.FILES, instance=profil_instance)
        profil = profil_form.save(commit=False)
        profil.save()
    elif request.GET.get('profil_id'):
        print("request found",request.GET.get('profil_id'))
        profil_id = request.GET.get('profil_id')
        profil = get_object_or_404(Profil, pk=profil_id)
        context =  {
            "profil": profil,
            "articles_selled_count_profil": Transaction.objects.filter(is_final=True, 
                                    invoice__seller_id=profil.user.id).count(),     
        }
        
        return render(request, 'user/profil-card.html', context)
            
    context = {
        'user_form': user_form,
        'profil_form': profil_form,
    }
    
    return render(request, 'user/profil.html', context)

@login_required
def logout_user(request):
    logout(request)
    return render(request, 'user/auto_login.html', {})

@login_required
def security(request):
    context = {}
    
    if request.GET.get('supprimer'):
        user = request.user
        user.is_active = False
        user.save()
        return redirect('store:home')

    if request.POST.get('new_password'):
        current_password = request.POST.get('current_password')
        new_password = request.POST.get('new_password')
        user = request.user
        
        if user.check_password(current_password):
            user.set_password(new_password)
            user.save()
            messages.add_message(request, messages.SUCCESS, 'Mot de passe modifié !')
            auth = authenticate(username=user.username, password=new_password)
            login(request, auth)
            return redirect('store:home')
        else:
            context['password_error'] = True
             
    return render(request, 'user/profil.html', context)  

user/templates/user/auto_login.html
{% extends 'base.html' %}
{% load socialaccount static %}
{% providers_media_js %}
{% block content %}
<div class="container body-page-content">
    <div class="row d-flex justify-content-center p-1 pt-5">
        <div class="border p-1 p-sm-2 rounded shadow bg-light box-login" >
            <div class="text-center">
                <h1 class="text-md">Inscription sur SC</h1>
                <p>Inscris-toi pour vendre ou acheter tes articles préférés en toute simplicité</p>
            </div>
            <div class="mt-4">
                <a href="{% provider_login_url 'google' %}" class="">
                    <img src="{% static 'user/images/gmail.png' %}" class="w-100 rounded" alt="gmail connexion">
                </a>
            </div>
            <div class="mt-4">
                <a href="{% provider_login_url 'facebook' %}" class="">
                    <img src="{% static 'user/images/fb.png' %}" class="w-100 rounded" alt="facebook connexion">
                </a>
            </div>
            <div class="mt-4 d-flex justify-content-around">
                <div><a href="{% url 'user:register' %}">S'inscrire</a></div>
                <div><a href="{% url 'user:login' %}">Se connecter</a></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user/templates/user/base.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
    <link rel="stylesheet" href="{% static 'user/css/user.css' %}">
{% endblock %}

{% block content %}
    
{% endblock %}

{% block scripts_links %}
    <script type="text/javascript" src="{% static 'user/js/user.js' %}"></script>
{% endblock %}

user/templates/user/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container body-page-content">
        <div class="d-flex justify-content-center">
            <div class="p-1 pt-5 text-center bloc-login w-100">
                <h1>Se connecter</h1>
                {% if error %}
                    <span class="alert">Mot de passe ou nom d'utilisateur incorect</span>
                {% endif %}
                <form action="{% url 'user:login' %}" method="post">
                    {% csrf_token %}
                    <div class="">
                        {{ form.as_p }}
                    </div>
                    
                    <div class="mt-4">
                        <button type="submit" class="btn btn-primary w-100">Connexion</button>
                    </div>
                    <div class="mt-4">
                        <a href="">Mot de passe oublié ?</a> <br>
                        <a href="{% url 'user:register' %}">Inscription ?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user/profil-card.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
<div class="body-page-content container-fluid pt-5 pb-5 p-sm-5 d-flex justify-content-center bg-secondary">
  <div class="card p-3" style="max-width: 640px;background: lightgrey;">
      <div class="row no-gutters">
        <div class="col-sm-4">
          <div class="row">
              <div class="col-6 col-sm-12">
                  <img src="{{ profil.avatar.url }}" style="max-width: 200px" class="card-img" alt="photo de profile">
              </div>
              <div class="col-6 col-sm-12">
                  <p class="card-text"><small class="text-muted">membre depuis le {{ profil.user.date_joined }}</small></p>
                  <p class="card-text"><small class="text-muted">Article déjà vendu : {{ articles_selled_count_profil }}</small></p>
              </div>
          </div>
        </div>
        <div class="col-sm-8 p-0">
          <div class="card-body">
            <h5 class="card-title">{{ profil.user.username }}</h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Nom complet : <br> <span class="text-primary"> {{ profil.user.first_name }} {{ profil.user.last_name }} </span></li>
              <li class="list-group-item">email : <a href="mailto:{{ profil.user.email }}" class="">{{ profil.user.email }}</a></li>
              <li class="list-group-item">whatsap : <a href="" class="">{{ profil.whatsap_number }}</a></li>
              <li class="list-group-item">Contact : <br> 
                <span class="d-block d-flex justify-content-around"> 
                  <a href="tel:{{ profil.contact_mtn }}" class="d-block">{{ profil.contact_mtn }}</a>  <a href="tel:{{ contact_airtel }}" class="d-block">{{ contact_airtel }}</a> 
                </span>
              </li>   
            </ul>
          </div>
        </div>
      </div>
  </div>
</div>
{% endblock %}

user/templates/user/profil.html
{% extends 'base.html' %}
{% block content %}
<div class="body-page-content container pt-4">
    <div class="row">
        <div class="col-12 col-md-5 text-sm-left mb-4 params-links">
            <h1 class="">Mes paramètres</h1>
            <ul class="list-group">
                <li class="list-group-item p-0 border-0">
                    <a href="{% url 'user:profil' %}" class="param-link d-block w-100 h-100 p-2 text-decoration-none text-secondary">Mon profile</a>
                </li>
                <li class="list-group-item p-0 border-0">
                    <a href="{% url 'user:profil' %}?profil_id={{ request.user.profil.id }}" class="param-link d-block w-100 h-100 p-2 text-decoration-none text-secondary">Aperçu carte de profil</a>
                </li>
                <li class="list-group-item p-0 border-0">
                    <a href="{% url 'user:security' %}" class="param-link d-block w-100 h-100 p-2 text-decoration-none text-secondary">Sécurité</a>
                </li>
            </ul>
        </div>
        
        <div class="col-12 col-md-7 update-profil">
            {% if request.path == '/user/profil/' %}
                <form action="{% url 'user:profil' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <br class="separator"/>
                    <div class="row d-flex align-items-center">
                        <div class="col-12 col-sm-4 text-sm-left">
                            <label for="">Photo de profil</label>
                        </div>
                        <div class="col-12 col-sm-4 text-center ">
                            {% if request.user.profil.avatar.url != "" %}
                                <img class='img-square img_chosen rounded-circle' src="{{ request.user.profil.avatar.url }}">
                            {% else %}
                                <img class='img-square img_chosen rounded-circle' src="../../../static/images/icons/stand.png">
                            {% endif %}
                        </div>
                        <div class="col-12 col-sm-4 text-sm-right">
                            <button class="btn-change-img btn btn-primary">Changer la photo</button>
                            <div hidden>
                                {{ profil_form.avatar }}
                            </div>
                        </div>
                    </div>
                    
                    <br class="separator">
                    
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Nom d'utiisateur</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right">
                            {{ user_form.username }}
                        </div>
                    </div>
                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Nom</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right">
                            {{ user_form.last_name }}
                        </div>
                    </div>
                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Prénom</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right">
                            {{ user_form.first_name }}
                        </div>
                    </div>

                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Email</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right">
                            {{ user_form.email }}
                        </div>
                    </div>
                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Contact MTN</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right mtn-number">
                            {{ profil_form.contact_mtn }}
                            <span class="text-danger d-none">Ceci n'est pas un numéro MTN valide</span>
                        </div>
                    </div>
                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Contact Airtel</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right airtel-number">
                            {{ profil_form.contact_airtel }}
                            <span class="text-danger d-none">Ceci n'est pas un numéro Airtel valide</span>
                        </div>
                    </div>
                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Whatsap</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right whatsap-number">
                            {{ profil_form.whatsap_number }}
                            <span class="text-danger d-none">Ceci n'est pas un numéro valide</span>
                        </div>
                    </div>

                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Numéro Airtel money</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right airtel-number">
                            {{ profil_form.airtel_money }}
                            <span class="text-danger d-none">Ceci n'est pas un numéro Airtel valide</span>
                        </div>
                    </div>

                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Numéro MTN money</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right mtn-number">
                            {{ profil_form.mtn_money }}
                            <span class="text-danger d-none">Ceci n'est pas un numéro MTN valide</span>
                        </div>
                    </div>

                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Sexe</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right">
                            {{ profil_form.gender }}
                        </div>
                    </div>

                    <br class="separator">
                    <div class="d-flex p-4 justify-content-around">
                        <a href="{% url 'store:home' %}" class="btn btn-danger d-block">Annuler </a>
                        <button type="submit" class="btn btn-primary d-block" id="save-update-profil-btn">Enregistrer</button>
                    </div>
                </form>
            {% elif request.path == '/user/security/' %}
                <h3 class="text-muted text-center mb-4">Modification mot de passe</h3>
                <form action="{% url 'user:security' %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Mot de passe actuel</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right">
                            {% if password_error %}
                                <span class="alert alert-warning d-block text-center" role="alert">Mot de passe invalide</span>
                            {% endif %}
                            <input type="password" name="current_password" value="">
                        </div>
                    </div>
                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Nouveau mot de passe</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right">
                            <input type="password" name="new_password" value="">
                            <span class="text-danger error-new-pswd"></span>
                        </div>
                    </div>
                    <br class="separator">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <label for="">Confirmer mot de passe</label>
                        </div>
                        <div class="col-12 col-sm-6 text-sm-right">
                            <input type="password" name="confirm_new_password" value="">
                            <span class="text-danger error-confirm-pswd"></span>
                        </div>
                    </div>
                    <br class="separator">
                    <div class="d-flex p-4 justify-content-around">
                        <a href="{% url 'store:home' %}" class="btn btn-danger d-block">Annuler </a>
                        <button type="submit" class="btn btn-primary d-block disabled"  id="save-pswd-btn">Enregistrer</button>
                    </div>
                </form>
                <a href="{% url 'user:security' %}?supprimer={{ request.user }}" type="button" class="mt-5 btn btn-danger btn-lg btn-block w-100 dialog_confirm_before">
                    Supprimer mon compte utilisateur
                    <span hidden>
                        Votre compte utilisateur sera supprimé de la plateforme ! <br>
                         vous ne pourrez plus vendre ou acheter avec ce compte.
                    </span>
                </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="container body-page-content">
        <div class="row d-flex justify-content-center">
            <div class="text-center box-register p-1 pt-5">
                <h1>Inscription</h1>
                
                {% if check_email %}
                <span class="alert text-warning">Cet email existe déjà</span>
                {% elif check_username %}
                <span class="alert text-warning">Nom d'utilisateur déjà existant</span>
                {% endif %}

                <form action="{% url 'user:register' %}" method="post">
                    {% csrf_token %}
                    <div class="bloc-login-input">
                        {{ form.as_p }}
                    </div>
                    <div class="mt-2">
                        <button type="submit" class="load-style btn btn-primary w-100">S'inscrire</button>
                    </div>
                    <div class="mt-2">
                        <a href="{% url 'user:login' %}" class="btn btn-outline-primary w-100">Connexion ?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}