dashboard/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    # re_path(r'^$', views.my_articles, name='my_articles'),
    # re_path(r'^delete/', views.delete_article, name='delete'),
    # re_path(r'^selled_list/$', views.selled_article_list, name='selled_list'),
    # re_path(r'^bought_list/$', views.bought_article_list, name='bought_list'),
    #ajout provisoire de url
    re_path(r'^factures/[a-z.ç]*', views.invoices, name="invoices"),
    re_path(r'^commandes/[a-zç]*$', views.orders, name="orders"),
    re_path(r'^payement/', views.payement, name="payement"),
    re_path(r'^achats-en-attentes/$', views.transactions, name="waiting-buy"),
    re_path(r'^ventes-en-attentes/$', views.transactions, name="waiting-sell"),
    re_path(r'^achats-effectués/$', views.transactions, name="articles-bought"),
    re_path(r'^ventes-réalisées/$', views.transactions, name="articles-selled"),
    re_path(r'^annuler-achat/$', views.transactions, name="cancel-transaction"),
]

app_name = 'dashboard'

store/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
    re_path(r'^supprimer-un-article/(?P<article_id>[0-9]+)/$', views.delete_article, name='delete'),
    re_path(r'^poster-un-article/', views.create_article, name="create_article"),
    re_path(r'^modifier-article/(?P<article_id>[0-9]+)/$', views.update, name='update'),
    re_path(r'^mes-favoris/$', views.favourite, name="favourite"),
    re_path(r'^mes-articles-ajoutés/$', views.my_articles_added, name="my_articles"),
    re_path(r'^rechercher-un-article/', views.search, name="search"),
]

app_name = 'store'

user/urls.py
from django.urls import re_path

from user import views

urlpatterns = [
    re_path(r'^login/', views.login_user, name="login"),
    re_path(r'^register/', views.register, name="register"),
    re_path(r'^auto_login/', views.auto_login, name="auto_login"),
    re_path(r'^profil/', views.profil, name="profil"),
    re_path(r'^security/', views.security, name="security"),
    re_path(r'^logout/', views.logout_user, name='logout'),
]

app_name = 'user'

dashboard/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save, post_delete
from django.db.models import F
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.core.cache import cache
from django.shortcuts import reverse

from store.models import Article
from communication.models import NotifMessage

class Order(models.Model):
    date_create = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, 
                             related_name="orders")
    article = models.OneToOneField(Article, on_delete=models.CASCADE)
    
class Invoice(models.Model):
    date_create = models.DateTimeField(auto_now_add=True)
    payed = models.BooleanField(default=False)
    article_name = models.CharField(max_length=100)
    description = models.TextField()
    quantity = models.PositiveIntegerField(default=1)
    delivery = models.BooleanField(default=False)
    price_init = models.PositiveIntegerField()
    price_ttc = models.PositiveIntegerField()
    seller_id = models.PositiveIntegerField()
    customer = models.ForeignKey(User, on_delete=models.CASCADE, 
                                 related_name="invoices")
    airtel_account_number = models.CharField(max_length=20, blank=True, null=True)
    mtn_account_number = models.CharField(max_length=20, blank=True, null=True)
    
    def seller(self):
        return User.objects.get(pk=self.seller_id)
    
class Transaction(models.Model):
    invoice = models.OneToOneField(Invoice, on_delete=models.CASCADE)
    date_create = models.DateTimeField(auto_now_add=True)
    details = models.CharField(max_length=200)
    is_final = models.BooleanField(default=False)
   
@receiver(post_save, sender=Invoice)
def after_save_invoice(sender, instance, **kwargs):
    #clear cache for customer
    cache.delete(f'invoices_{instance.customer.id}')
    
@receiver(post_delete, sender=Invoice)    
def after_delete_invoice(sender, instance, **kwargs):
    """do some action after delete or cancel invoice
    """
    #clear cache invoice for customer 
    cache.delete(f'invoices_{instance.customer.id}')

@receiver(pre_save, sender=Order)
def post_save_order(sender, instance, **kwargs):
    """Do some actions after create order"""
    #decremente article number after ordering
    article = instance.article
    article.number -= 1
    article.save()
    
    #send notif to seller's article
    msg = f"Salut {article.user}, vous avez une commande de l'article \"{article} \
        identifiant: {article.id}\" que vous avez posté ! Veuillez valider ou\
             décliner la commande de votre client en cliquant sur ce message"
    NotifMessage.objects.create(
        user=article.user,
        content=msg,
        link=f"{reverse('dashboard:orders')}reçues",
    )

dashboard/forms.py
from django import forms
import re

from .models import Order

class OrderForms(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('customer', 'article')
        
class MomoNumber(forms.Form):
    DATA_ATTRS = {"class": "form-control input-number", "placeholder": "+242"}
    mtn_account_number = forms.IntegerField(required=False)
    confirm_number_mtn = forms.IntegerField(required=False)
    airtel_account_number = forms.IntegerField(required=False)
    confirm_number_airtel = forms.IntegerField(required=False)
    
    mtn_account_number.widget.attrs.update(DATA_ATTRS)
    confirm_number_mtn.widget.attrs.update(DATA_ATTRS)
    airtel_account_number.widget.attrs.update(DATA_ATTRS)
    confirm_number_airtel.widget.attrs.update(DATA_ATTRS)

    
    
    

dashboard/views.py
from django.shortcuts import redirect, render, reverse, get_object_or_404, HttpResponse
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.cache import cache
from django.contrib import messages

from store.models import Article, Category
from .models import Order, Invoice, Transaction
from communication.models import Message
from .forms import OrderForms, MomoNumber
from store.forms import ArticleForms
from store.utils import add_percentage

# @login_required
# def my_articles(request):
#     def get_article(availability=True):
#         return Article.objects.filter(Q(user=request.user) & \
#             Q(available=availability))
    
#     if not cache.get(f'available_articles_{request.user.id}') and not \
#             cache.get(f'unavailable_articles_{request.user.id}'):        
#         cache.set(f'available_articles_{request.user.id}', get_article(True))
#         cache.add(f'unavailable_articles_{request.user.id}', get_article(False))
    
#     context ={
#         'articles_available_of_seller': cache.get(f'available_articles_{request.user.id}'),
#         'articles_unavailable_of_seller': cache.get(f'unavailable_articles_{request.user.id}'),
#     }
#     return render(request, 'dashboard/my_articles.html', context)

# @login_required
# def selled_article_list(request):
#     context = {
#         'page_name': 'ARTICLES VENDUS',
#     }
#     return render(request, 'dashboard/archives.html', context)

# @login_required
# def bought_article_list(request):
#     context = {
#         'page_name': 'ACHATS EFFECTUÉS',
#     }
    
#     return render(request, 'dashboard/archives.html', context)

# @login_required
# def delete_article(request):
#     #update availability
#     if request.GET.get('availability'):
#         id = request.GET.get('availability')
#         id = int(id)
#         article = get_object_or_404(Article, id=id)
#         if article.available == True:
#             article.available = False
#         else:
#             article.available = True
            
#         article.save()
#         cache.clear()
        
#         return redirect('dashboard:my_articles')
    
#     if request.GET.get('article_id'):
#         id = request.GET.get('article_id')
#         id = int(id)
#         article = get_object_or_404(Article, id=id)
#         #connect info messaage with action in models
#         article.delete()
#         cache.clear()
#         #show message success
#         messages.success(request, article_delete_success(article))
    
#     return redirect('dashboard:my_articles')

@login_required
def invoices(request):
    #create invoice if argument == order_id
    if request.GET.get('order_id'):
        order_id = request.GET.get('order_id')
        order = get_object_or_404(Order, pk=order_id)
        # verify if order.article.user is for current user
        if order.article.user != request.user:
            raise Http404
        
        mtn_number = request.GET.get("mtn_account_number")
        airtel_number = request.GET.get("airtel_account_number")
        
        if not MomoNumber(request.GET).is_valid():
            import pdb;pdb.set_trace()
        
        try:
            invoice = Invoice(
                article_name=order.article.name,
                description=order.article.description,
                delivery=order.article.delivery,
                price_init=order.article.price_init,
                price_ttc=order.article.price_ttc,
                customer=order.customer,
                seller_id=order.article.user.id,
            )
            if airtel_number != "":
                invoice.airtel_account_number=int(airtel_number)
            if mtn_number != "":
                invoice.mtn_account_number=int(mtn_number)
            
            invoice.save()
            
            order.delete()
            cache.clear()
        except Exception as e:
            print(f"Error => {e}")
        
        return redirect("/gestion/commandes/reçues")
    #delete or cacncel invoice if argument == invoice__id
    if request.GET.get('invoice_id'):
        invoice_id = request.GET.get('invoice_id')
        invoice = get_object_or_404(Invoice, pk=invoice_id)
        #verify if invoice is for current user
        if invoice.customer != request.user:
            raise Http404
        invoice.delete() #remove invoice
    
    cache_time = (30*60)
    if not cache.get(f"invoices_{request.user.id}"):
        cache.set(f"invoices_{request.user.id}", Invoice.objects.filter\
                (Q(customer=request.user) & Q(payed=False)), cache_time)
        
    context = {
        "invoices": cache.get(f"invoices_{request.user.id}")
    }
        
    return render(request, 'dashboard/invoice.html', context)

@login_required
def orders(request):
    path_base = "/gestion/commandes/"
    context = {}
    #if request post contain article_id, create new order
    if request.GET.get('article_id'):
        article_id = request.GET.get('article_id')
        article = get_object_or_404(Article, pk=article_id)
        if article.number > 0:
            Order.objects.create(customer=request.user, article=article)
        else:
            messages.info(request, "Désolé l'article {article} a déjà été \
                commandé !")
            return redirect('store:detail', article.id) 

        article.save()
        cache.clear()
        return redirect(f"{path_base}envoyees")
    
    if request.GET.get('order_id'):
        order_id =  request.GET.get('order_id')
        order = get_object_or_404(Order, pk=order_id)
        
        if request.GET.get('valider-la-commande'):
            context = {
                "order": order,
                "form": MomoNumber(),
            }
            return render(request, 'dashboard/form-number-account.html', context)
        
        order.delete()
        #clear cache
        cache.clear()
        if request.GET.get('annuler-la-commande'):
            return redirect("/gestion/commandes/envoyees")

        return redirect(f"{path_base}reçues")
    
    cache_time = (30*60)#set cache time            
    
    #conditional part of page to show
    if request.path == f"{path_base}envoyees" or request.path == path_base:
        context['path'] = request.path
        #get sent orders unmanaged
        if not cache.get(f'orders_send_{request.user.id}'):
            cache.set(f'orders_send_{request.user.id}', Order.objects.filter\
                    (customer=request.user), cache_time) 
        context["orders"] = cache.get(f'orders_send_{request.user.id}')
    elif request.path == f"{path_base}reçues":
        context['path'] = request.path
        #get received orders unmanaged
        if not cache.get(f'orders_receive_{request.user.id}'):
            cache.set(f'orders_receive_{request.user.id}', Order.objects.filter\
                    (article__user=request.user), cache_time)
        context["orders"] = cache.get(f'orders_receive_{request.user.id}')
        
    return render(request, 'dashboard/order.html', context)


@login_required
def transactions(request):
    context = {}
    
    if request.GET.get("transaction_id") and request.path == "/gestion/annuler-achat/":
        transaction_id = request.GET.get("transaction_id")
        transaction = get_object_or_404(Transaction, pk=transaction_id)
       
        transaction.delete()
    
    if request.path ==  "/gestion/achats-en-attentes/":
        if not cache.get(f"transactions_waiting_{request.user.id}"):
            cache.set(f"transactions_waiting_{request.user.id}", Transaction.objects.\
                filter(Q(invoice__customer=request.user) & Q(is_final=False)), 60 * 15)
        context["transactions"] = cache.get(f"transactions_waiting_{request.user.id}")
    
    elif request.path == "/gestion/achats-effectués/":
        if not cache.get(f"articles_bought_{request.user.id}"):
            cache.set(f"articles_bought_{request.user.id}", Transaction.objects.\
                filter(Q(invoice__customer=request.user) & Q(is_final=True)), 60 * 15)
        context["transactions"] = cache.get(f"articles_bought_{request.user.id}")
    
    elif request.path == "/gestion/ventes-réalisées/":
        if not cache.get(f"articles_selled_{request.user.id}"):
            cache.set(f"articles_selled_{request.user.id}", Transaction.objects.\
                filter(Q(invoice__seller_id=request.user.id) & Q(is_final=True)), 60 * 15)
        context["transactions"] = cache.get(f"articles_selled_{request.user.id}")
  
    elif request.path == "/gestion/ventes-en-attentes/":
        if not cache.get(f"articles_selled_{request.user.id}"):
            cache.set(f"articles_selled_{request.user.id}", Transaction.objects.\
                filter(Q(invoice__seller_id=request.user.id) & Q(is_final=False)), 60 * 15)
        context["transactions"] = cache.get(f"articles_selled_{request.user.id}")
        
    return render(request, "dashboard/transactions.html", context)

@login_required
def payement(request):
    invoice_id = request.GET.get('invoice_id')    
    invoice = get_object_or_404(Invoice, pk=invoice_id)
    
    if request.POST:
        operator = request.POST.get('operator')
        account_number = request.POST.get('account-number')
        
        # import pdb;pdb.set_trace();
        
    context = {
        "invoice": invoice
    }
    return render(request, 'dashboard/payement-processus.html', context)

dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="body-page-content pt-4 container-fluid">
        <div class="d-flex d-md-none justify-content-between">
            <img src="{% static 'node_modules/bootstrap-icons/icons/menu-up.svg' %}" 
            alt="Bootstrap" width="25" height="25" class="pointer down-menu">
            <h1 class="font-md text-center">TABLEAU DE BORD</h1>
        </div>
        <div class="row">
            <div class="col-md-4 d-none d-md-block dash-menu">
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center bg-primary text-light">
                        Achat
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'dashboard:orders' %}envoyees" class="dash-link list-group-item d-flex justify-content-between align-items-center">
                        Commande{{ orders_sended_count|pluralize }} envoyée{{ orders_sended_count|pluralize }}
                        {% if orders_sended_count >= 1 %} 
                            <span class="badge bg-primary ">{{ orders_sended_count }}</span>
                        {% endif %}
                        </a>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'dashboard:invoices' %}" class="dash-link list-group-item d-flex justify-content-between align-items-center">
                            Facture{{ invoices|pluralize }} à payer
                            {% if invoices.count >= 1 %} 
                                <span class="badge bg-primary ">{{ invoices.count }}</span>
                            {% endif %}
                        </a>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{% url 'dashboard:waiting-buy' %}" class="dash-link list-group-item d-flex justify-content-between align-items-center w-100">
                            Achat{{ orders|pluralize }} à finaliser
                            {% if waiting_transactions_count >= 1 %} 
                                <span class="badge bg-primary ">{{ waiting_transactions_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{% url 'dashboard:articles-bought' %}" class="dash-link list-group-item d-flex justify-content-between align-items-center w-100">
                            Achat{{ final_transactions_count|pluralize }} réalisé{{ final_transactions_count|pluralize }}
                            {% if final_transactions_count >= 1 %} 
                                <span class="badge bg-primary ">{{ final_transactions_count }}</span>
                            {% endif %}
                        </a>
                    </li>

                    <li class="list-group-item d-flex justify-content-between align-items-center bg-primary text-light">
                        Vente
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'dashboard:orders' %}reçues" class="dash-link list-group-item d-flex justify-content-between align-items-center">
                            Commande{{ orders|pluralize }} reçue{{ orders|pluralize }}
                            {% if orders_received_count >= 1 %}
                                <span class="badge bg-primary badge-pill">{{ orders_received_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'dashboard:waiting-sell' %}" class="dash-link list-group-item d-flex justify-content-between align-items-center">
                            Vente{{ articles_selled_count|pluralize }} en attente{{ articles_selled_count|pluralize }}
                            {% if articles_selled_count >= 1 %}
                                <span class="badge bg-primary badge-pill">{{ articles_selled_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'dashboard:articles-selled' %}" class="dash-link list-group-item d-flex justify-content-between align-items-center">
                            Vente{{ articles_selled_count|pluralize }} réalisée{{ articles_selled_count|pluralize }}
                            {% if articles_selled_count >= 1 %}
                                <span class="badge bg-primary badge-pill">{{ articles_selled_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                </ul>
            </div> 
            <div class="col-md-8">
                {% block pageContent %}

                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/form-number-account.html
{% extends 'base.html' %}
{% block content %}
    <div class="body-page-content pt-4 container">

        <div class="row">
            <h1 class="text-center text-primary font-sm-md">
                Confirmez un ou deux numéros mobile money pour la reception de votre argent électronique
             </h1>
        </div>

        <form action="{% url 'dashboard:invoices' %}" method="GET" class="p-2 form-account-momo text-primary">
            <div class="row border p-4 form-account-momo-mtn">
                <h3>Si MTN </h3>
                <div class="col-sm-6">
                  <label for="inputTel">Numéro</label>
                  {{ form.mtn_account_number }}
                  <span class="error-mtn-number text-danger d-none">Ceci n'est pas un numéro MTN conforme</span>
                </div>
                <div class="col-sm-6">
                  <label for="inputTel">Confirmez numéro</label>
                  {{ form.confirm_number_mtn }}
                  <span class="error-equal-mtn text-danger d-none">Les numéros diffèrent</span>
                </div>
            </div>

            <div class="row border p-4 mt-3 form-account-momo-airtel">
                <h3>Si Airtel </h3>
                <div class="col-sm-6">
                  <label for="inputTel">Numéro</label>
                  {{ form.airtel_account_number }}
                  <span class="error-airtel-number text-danger d-none">Ceci n'est pas un numéro airtel conforme</span>
                </div>
                <div class="col-sm-6">
                  <label for="inputTel">Confirmez numéro</label>
                  {{ form.confirm_number_airtel }}
                  <span class="error-equal-airtel text-danger d-none">Les numéros diffèrent</span>
                </div>
            </div>
            <input type="text" hidden name="order_id" value="{{ order.id }}">
            <div class="text-center mt-2">
                <button class="btn btn-primary m-0 valid-number-btn" type="submit" disabled="true">Validez vos coordonnées</button>
            </div>
        </form>
    </div>
{% endblock %}

dashboard/templates/dashboard/invoice.html
{% extends 'dashboard/dashboard.html' %}
{% block pageContent %}
<div class="">
    <div class="row">
        <div class="col-12">
            <h3 class="font-md border-bottom">MES FACTURES A PAYER</h3>
        </div>
    </div>

    <div class="row">
        {% for invoice in invoices %}
            <div class="col-12 col-md-6 mt-4">
                <table class="table font-sm">
                    <thead class="bg-dark text-light">
                      <tr>
                        <th scope="col" colspan="2"># Facture n° {{ invoice.id }}</th>
                      </tr>
                      <tr>
                        <th colspan="2">date : {{ invoice.date_create }}</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">Nom d'article</th>
                        <td>{{ invoice.article_name }}</td>
                      </tr>
                      <tr>
                        <th scope="row">Description</th>
                        <td>{{ invoice.description }}</td>
                      </tr>
                      <tr>
                        <th scope="row">Prix TTC</th>
                        <td>{{ invoice.price_ttc }}</td>
                      </tr>
                      <tr>
                        <th scope="row">Livraison</th>
                        <td>
                          {% if invoice.delivery %} 
                            Possible
                          {% else %}
                            Pas de livraison
                          {% endif %}
                        </td>
                      </tr>
                      <tr>
                        <th scope="row">Etat de l'article</th>
                        <td>{{ invoice.status }}</td>
                      </tr>
                    </tbody>
                  </table>
                <div class="row3">
                    <div class="col-12">
                        <a href="{% url 'dashboard:payement' %}?invoice_id={{ invoice.id }}" class="btn btn-success w-100 dialog_confirm_before">
                            Valider payement article
                            <span class="d-none">
                                En validant le payement, l'argent sera transmis dans un premier temps sur le compte électronique
                                de spectrecorp, par la suite vous ne finalisez le payement que si vous avez pu contacter le vendeur
                                via les coordonnées que spectrecorp vous enverra et  que vous avez l'article en votre possession ! <br>
                                le cas échéant vous pouvez toujours annuler le payement et recupérer votre argent électronique !!! <br>
                                
                            </span>
                        </a>
                    </div>
                    <div class="col-12 mt-1">
                        <a href="{% url 'dashboard:invoices' %}?annuler-payement={{ invoice.article }}?&amp;invoice_id={{ invoice.id }}"
                        class="btn btn-danger w-100 dialog_confirm_before">
                           Annuler payement article
                           <span class="d-none">Vous annulez le payement de l'article {{ invoice.article_name }}</span>
                        </a>
                    </div>
                </div>
            </div>
        {% empty %}
          <div class="col-12 pmd-5 pt-5 pb-5">
            <p class="m-auto pmd-5 text-center font-weight-bold bg-info">
              Aucune facture à payer
            </p>
          </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/payement-processus.html
{% extends 'base.html' %}
{% block content %}
    <div class="body-page-content pt-4 container-fluid">
        <h1>Processus achat</h1>
        <form action="{% url 'dashboard:payement' %}?invoice_id={{ invoice.id }}" method="post">
            {% csrf_token %}
            <div class="card border-primary mb-3 select-momo m-auto" style="max-width: 18rem;">
                <div class="card-header text-center">Selection opérateur</div>
                <div class="card-body text-primary">
                    <div class="form-check form-check">
                        <input class="form-check-input" type="radio" name="operator" id="inlineRadio1" checked value="mtn">
                        <label class="form-check-label" for="inlineRadio1">MTN Money</label>
                    </div>
                    <div class="form-check form-check mt-4">
                        <input class="form-check-input" type="radio" name="operator" id="inlineRadio2" value="airtel">
                        <label class="form-check-label" for="inlineRadio2">Airtel Money</label>
                    </div>
                </div>
            </div>

            <div class="card border-primary mb-3 select-momo m-auto" style="max-width: 18rem;">
                <div class="card-header text-center">Entrez le numéro du compte à débiter</div>
                <div class="card-body text-primary">
                    <div class="form-group">
                        <label for="account-number" class="text-center label-number">Numéro mobile money</label>
                        <input type="number" class="form-control form-number-input" id="account-number" name="account-number"><br>
                        <span class="text-danger error-operator-number"></span>
                    </div>
                </div>
            </div>

            <div class="text-center d-flex justify-content-center">
                <a href="{% url 'dashboard:invoices' %} " class="btn btn-danger m-2">Annuler</a>
                <button type="submit" class="btn btn-success m-2" id="btn-valid-number" disabled="true">Valider</button>
            </div>
        </form>
    </div>
{% endblock %}

dashboard/templates/dashboard/update_article.html
{% extends 'store/base.html' %}
{% block content %}
<div class="container" style="padding-top: 100px;">
    <form action="{% url 'store:update' article_id=article.id %}" method="post" 
    enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'store/article_forms.html' %}
    </form>
</div>
{% endblock %}