communication/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^chat-message/(?P<article_id>[0-9]+)/$', views.chat_message, name="chat_message"),
    re_path(r'^box_message/', views.box_msg, name="box_msg"),
    re_path(r'^notifications/', views.notifications, name="notifications"),
    re_path(r'^redirect-from-notif/', views.notif_detail, name="notif_redirect"),
]

app_name = "communication"

dashboard/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    # re_path(r'^$', views.my_articles, name='my_articles'),
    # re_path(r'^delete/', views.delete_article, name='delete'),
    # re_path(r'^selled_list/$', views.selled_article_list, name='selled_list'),
    # re_path(r'^bought_list/$', views.bought_article_list, name='bought_list'),
    #ajout provisoire de url
    re_path(r'^factures/[a-z.ç]*', views.invoices, name="invoices"),
    re_path(r'^commandes/[a-zç]*$', views.orders, name="orders"),
    re_path(r'^payement/', views.payement, name="payement"),
    re_path(r'^achats-en-attentes/$', views.transactions, name="waiting-buy"),
    re_path(r'^ventes-en-attentes/$', views.transactions, name="waiting-sell"),
    re_path(r'^achats-effectués/$', views.transactions, name="articles-bought"),
    re_path(r'^ventes-réalisées/$', views.transactions, name="articles-selled"),
    re_path(r'^annuler-achat/$', views.transactions, name="cancel-transaction"),
]

app_name = 'dashboard'

store/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
    re_path(r'^supprimer-un-article/(?P<article_id>[0-9]+)/$', views.delete_article, name='delete'),
    re_path(r'^poster-un-article/', views.create_article, name="create_article"),
    re_path(r'^modifier-article/(?P<article_id>[0-9]+)/$', views.update, name='update'),
    re_path(r'^mes-favoris/$', views.favourite, name="favourite"),
    re_path(r'^mes-articles-ajoutés/$', views.my_articles_added, name="my_articles"),
    re_path(r'^rechercher-un-article/', views.search, name="search"),
]

app_name = 'store'

user/urls.py
from django.urls import re_path

from user import views

urlpatterns = [
    re_path(r'^login/', views.login_user, name="login"),
    re_path(r'^register/', views.register, name="register"),
    re_path(r'^auto_login/', views.auto_login, name="auto_login"),
    re_path(r'^profil/', views.profil, name="profil"),
    re_path(r'^security/', views.security, name="security"),
    re_path(r'^logout/', views.logout_user, name='logout'),
]

app_name = 'user'

templates/base-ex.html
<!DOCTYPE html>
<html lang="fr">
{% load static pwa cache %}
<head>
    <meta charset="UTF-8">
    {% include 'head.html' %}
    {% block links %}
    {%  endblock %}
    {% progressive_web_app_meta %} 
    <title>SC</title>
</head>
<body>
    <div class="container-fluid about" 
    {% if not white_font %} style="background: #ebedee; padding-right: 10px; padding-left: 10px;" {% endif %}>
        <header class="container-fluid">
            <div class="row h_line1">
               <div class="col-lg-1 font-weight-bold corner-left">
                    {% cache 1000 logo %}
                        <div id="logo">
                            <a href="{% url 'store:home' %}"><img src="{% static 'images/icons/Logo.jpg' %}" alt="logo"></a>
                        </div>
                    {% endcache %}

                    {% if user.is_authenticated %}
                    <div class="bloc_conected">
                        <div class="conected-elts conected1" style="display: flex; justify-content: space-around;">
                            {% include 'icons.html' %}
                        </div>
                    </div>
                    {% endif %}
                    
                    <div class="menu-btn">
                        <button class=" menu-icon btn1" type="button"></button>
                        <button class=" menu-icon btn2" type="button" style="display: none;"></button>
                    </div>
               </div> 
               
               <!-- Menu for mobile phone only -->
               <div id="mobile-menu">
                   <div class="bloc_1">

                        <div class="btn_sell">
                            <a href="{% url 'store:create_article' %}"><button>Vendre un article</button></a>
                        </div>
                        {% if not user.is_authenticated %}
                            <div class="login">
                                <div><a href="{% url 'user:auto_login' %}" class="link1">S'inscrire</a></div><span class="separator"></span>
                                <div><a href="{% url 'user:auto_login' %}" class="link2">Se connecter</a></div>
                            </div>
                        {% endif %}
                        <div class="guide">
                            <a href="{% url 'work_step' %}"><button>Voir notre guide</button></a>
                        </div>
                   </div>

                   <hr>

                   <div class="bloc_2">
                        <h3>Navigation</h3>
                        <nav>
                            <ul>
                                {% if user.is_authenticated %}
                                    <li><a href="{% url 'user:logout' %}">Se deconnecter</a></li>
                                {% endif %}
                                <li><a href="{% url 'store:home' %}">Acceuil</a></li>
                                {% if user.is_authenticated %}
                                    <li><a href="{% url 'store:my_articles' %}">Mes articles ajoutés</a></li>
                                    <li><a href="{% url 'dashboard:my_articles' %}">Tableau de bord</a></li>
                                {% endif %}
                                <li><a href="{% url 'about' %}">A propos</a></li>
                            </ul>
                        </nav>
                   </div>

                   <div class="bloc_3">
                        <h3>Découvrez</h3>
                        <nav>
                            <ul>
                                <li><a href="{% url 'work_step' %}">Comment ça marche</a></li>
                                <li><a href="{% url 'about' %}?#apps">Applications mobiles</a></li>
                            </ul>
                        </nav>
                   </div>

                   <div class="bloc_4">
                        <h3>Entreprise</h3>
                        <nav>
                            <ul>
                                <li><a href="{% url 'about' %}">A propos de SC</a></li>
                                <li><a href="{% url 'contact' %}">Contactez-nous</a></li>
                            </ul>
                        </nav>
                   </div>
                  
               </div>

               {% cache 1000 search_input %}
                <div class="col-lg-5  corner-center b_h">
                    <form action="{% url 'store:search' %}" method="GET" >
                            <div class="row">
                                <div id="category-elt">
                                    <select name="category" id="list-catgegory">
                                        <option value="all">Tous</option>
                                        {% for category in categories %}
                                            <option value="{{ category.name }}">{{ category.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div id="search-element">
                                    <div class="child-1 d-flex">
                                        <div class="col-md-2">
                                            <input type="submit" value="cate">
                                        </div>
                                        <div class="col-md-10">
                                            <input type="text" id="search-elt" name="query" placeholder="Rechercher des articles">
                                        </div>
                                    </div>
                                    <div>
                                        <button id="cancel-search">
                                        </button>
                                    </div>
                                        
                                    <div class="result-search-zone">
                                        
                                    </div>
                                </div>
                        </div>
                        <input type="submit" id="valid-search" style="display: none;" class="load-style">
                    </form>
                </div>
               {% endcache %}

                <div class="col-lg-6  corner-right ">
                    <div class="row">
                    
                        {% if user.is_authenticated %}
                            <div class="conected-elts conected2" style="display: flex; justify-content: space-around;
                            width: 50%;">
                                {% include 'icons.html' %}
                            </div>
                        {% else %}
                            <div class="connected-link">
                                <a href="{% url 'user:auto_login' %}">S'inscrire </a>
                                <span class="vertical-line"> </span>
                                <a href="{% url 'user:auto_login' %}"> Se connecter </a>
                            </div>
                        {% endif %}

                        <a href="{% url 'store:create_article' %}"><button>Vendre un article</button></a>
                        <div class="patch-question"> 
                            <a href="{% url 'work_step' %}"></a>
                        </div>
                    </div>
                </div>
                
            </div>
            
            <nav class="navbar navbar-expand-lg ">
                <div id="navbarContent" class="collapse navbar-collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item active"><a href="{% url 'store:home' %}" class="nav-link">Acceuil</a></li>
                        <li class="nav-item"><a href="{% url 'about' %}" class="nav-link">À propos</a></li>
                        <li class="nav-item"><a href="{% url 'contact' %}" class="nav-link">Contact</a></li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a href="{% url 'store:my_articles' %}" class="nav-link">Mes articles ajoutés</a></li>
                            <li class="nav-item"><a href="{% url 'dashboard:my_articles' %}" class="nav-link">Tableau de bord</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            
            <div class="row">
                <div class="col-12 d-flex justify-content-center flex-column align-items-center alert-notifs">
                    {% if messages %}
                        {% for message in messages %}
                         <li class="alert-notif {{ message.tags }}">
                             {{ message }} <span class="remove-notif">x</span> 
                        </li>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>

        </header>
        <div class="center-body">
            <div class="pages-content">
                {% block content %}
                {% endblock %}
            </div>
            <div class="load-deco" style="display: none;">
                <img src="{% static 'images/icons/loading.gif' %}" width="50" class="loading" alt="">
            </div>
        </div>

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base_script.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}" ></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    
    {% block scripts_links %}
    {% endblock %}

    
    <script type="text/javascript">
        $(function(){
            /****Favourite avent to add */
            $('.save-favourite, #action .add-btn').click( function(){
                let article_id = $(this).attr('id');
                $.get('{% url "store:favourite" %}?article_id=' + article_id);
                $(this).hide()
            });
            /*********Favourite evennt to remove*/
            $('.delete-favourite').click( function(){
                let article_id = $(this).attr('id');
                $.get('{% url "store:favourite" %}?delete_article_id=' + article_id);
                $('.card'+article_id).hide();
            });

            /**********ARTICLE EVENT***********/
            /**DELETE***/
            $('.btn-delete').click( function(){
                let article_id = $(this).attr('id');
                $.get('{% url "dashboard:delete" %}?article_id=' + article_id);
            });
            /***update availability***/
            $('.available-btn').change( function(){
                let article_id = $(this).attr('id');
                $.get("{% url 'dashboard:delete' %}?availability=" + article_id);
                $('body').html('');
                $('body').load("{% url 'dashboard:my_articles' %}");
            });

            /***LOGIN HIDE/SHOW PASSWORD****/
            let pInput = $('.bloc-login-input p:last');
            let inputElt = $('.bloc-login-input p:last input');
            let pwdInput = $('.icons-hide-show')
            
            let imgHide = document.createElement('img');
            $(imgHide).attr({
                'src': '{% static "user/images/hide.png" %}',
                "width": '20',
                "height": '20',
            }).css('cursor', 'pointer');
            
            let imgShow = document.createElement('img');
            $(imgShow).attr({
                'src': '{% static "user/images/show.png" %}',
                "width": '20',
                "height": '20',
            }).css('cursor', 'pointer');


            pInput.append(imgHide);
            pInput.append(imgShow);
            pwdInput.append(imgShow);
            pwdInput.append(imgHide);

            $(imgShow).hide()

            $(imgHide).click(()=>{
                $(imgHide).toggle()
                $(imgShow).toggle()
                $('.inputForm').attr('type', 'text')
            });
            $(imgShow).click(()=>{
                $(imgHide).toggle()
                $(imgShow).toggle()
                $('.inputForm').attr('type', 'password')
            });
        
        
            /***Infinite scroll script**/
            let infinite = new Waypoint.Infinite({
                element: $('.infinite-container')[0],
                offset: 'bottom-in-view',
                onBeforePageLoad: function(){

                },
                onAfterPageLoad: function(){
                    
                }

            })        
        })
    
    </script>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <!-- <link rel="stylesheet" href="{% static 'communication/css/message.css' %}"> -->
    <!-- <link rel="stylesheet" href="{% static 'css/base.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/style_sass.css' %}">
</head>
<body>
  <div class="container-fluid p-0">
    <!-- ============================BEGIN_HEADER=========================================== -->
    <header class="p-2 w-100 bg-light">
      <div class="p-2 row row-cols-3">
        <div class="col-2 col-md-1 p-0 bg">
          <div class="logo">
            <a href="{% url 'store:home' %}"><img class="rounded-circle" src="{% static 'images/icons/logo_min.png' %}" alt="logo"></a>
          </div>
        </div>
        <div class="col-8 col-md-4 order-md-3 d-flex justify-content-end">
          {% if request.user.is_authenticated %}
            <div class="d-flex justify-content-end account-info m-0 mt-0 mb-0">
              <div class="account-info__access p-1 pt-0 pb-0">
                <a href="{% url 'communication:box_msg' %}">
                  <img class="" src="{% static 'images/icons/chat.png' %}" alt="chat">
                  <span class="account-info__access__badge">
                    {% if message_count > 0 %} {{ message_count }} {% endif %}
                  </span>
                </a>
              </div>
            
              <div class="account-info__access p-1 pt-0 pb-0">
                <a href="{% url 'communication:notifications' %}">
                  <img class="" src="{% static 'images/icons/notif.png' %}" alt="notif">
                  <span class="account-info__access__badge">
                    {% if notif_count > 0 %} {{ notif_count }} {% endif %}
                  </span>
                </a>
              </div>
            
              <div class="account-info__access avatar">
                <a href="{% url 'user:profil' %}" class="dropdown-toggle w-auto show-menu-fixed">
                  {% if request.user.profil.avatar.url != '' %}
                    <img src="{{ request.user.profil.avatar.url }}" alt="avatar" class="img-avatar img-square rounded-circle">
                  {% else %}
                    <img src="{% static 'images/icons/stand.png' %}" alt="avatar" class="img-avatar img-square rounded-circle">
                  {% endif %}
                </a>
              </div>

              <ul class="list-group fixed-bloc-links d-none">
                <a href="{% url 'user:profil' %}" class="text-light list-group-item bg-secondary font-sm">Profile</a>
                <a href="{% url 'user:logout' %}" class="text-light list-group-item bg-secondary font-sm">Déconnexion</a>
              </ul>

            </div>

            <a href="{% url 'store:create_article' %}" class="btn text-light text-truncate btn-style d-none d-md-block text-truncate w-100 bg-primary text-decoration-none">
                Poster article</a>
          {% else %}
            <button type="button" class="text-secondary btn-style d-none d-md-block text-truncate w-100 bg-light">
              <a href="{% url 'user:auto_login' %}">s'inscrire | se connecter</a>
            </button>
          {% endif %}

          <div class="p-2 icon-question d-flex justify-content-center align-items-center">
            <a href="{% url 'work_step' %}">
              <img class="d-none d-lg-block" src="{% static 'images/icons/patch-question.png' %}" alt="comment ça marche">
            </a>
          </div>
        </div>
        
        <div class="col-2 p-0 d-md-none">
          <div class="menu-icon d-flex justify-content-end">
            <img class="h-100 pointer" src="{% static 'images/icons/menu-up.png' %}" alt="menu">
          </div>
        </div>      
  
        <hr class="w-100 d-md-none mt-0 mt-sm-1 mb-2"/>
  
        <div class="col-12 col-md-7 order-md-2 p-0">
          <form class="d-flex bg-primary form_search" action="{% url 'store:search' %}" method="get">
            <div class="form_search__select">
              <select name="category" id="" class="h-100 bg-primary border-0 text-light">
                <option value="all">Trier</option>
                {% for category in categories %}
                  <option value="{{ category.name }}">{{ category.name }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="d-flex justify-content-start form_search__input w-100">
              <div class="">
                <input type="submit" value="" class="h-100 rounded-0 border-0 form_search__input_submit">
              </div>
              <div class="w-100">
                <input type="text" name="query" class="h-100 w-100 rounded-0 border-0 text-secondary form_search__input_text">
              </div>
            </div>
          </form>
        </div>  
      </div>

      <hr class="m-1 mt-1 d-none d-md-block"/>

      <nav class="d-none d-md-inline">
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:home' %}">Acceuil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'about' %}">A propos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:my_articles' %}">Mes articles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link dashboard-link" href="{% url 'dashboard:orders' %}envoyees">Tableau de bord</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:favourite' %}">Favoris</a>
          </li>
          <li class="nav-item d-none d-lg-block">
            <a class="nav-link" href="{% url 'communication:notifications' %}">Notifications 
              {% if notif_count > 0 %}<span class="badge bg-primary">{{ notif_count }}</span></a>{% endif %}
          </li>
          {% endif %}
        </ul>
      </nav>

      <hr class="m-1 mt-1 d-none d-md-block"/>
      {% if messages %}
      <div class="alerts top-alerts text-center w-100">
        {% for message in messages %}
        <div {% if message.tags %}
              class="alert text-center alert-{{ message.tags }} font-sm-md text-primary"
              {% else %}
              class="alert alert-info font-sm-md"
              {% endif %}> 
          {{ message }}</div>
        {% endfor %}
      </div>
      {% endif %}
    </header>
    <!--=============================END_HEADER-->


    <!--=============================BEGIN CONTENT PAGE BODY=================================-->
    <div id="central-page" class="">
      {% block content %} {% endblock %}
      <!--=============================END CONTENT PAGE BODY=================================-->
      {% include 'confirmation_dialog.html' %}
    </div>

    <div id="mobile-menu" class="row bg-light h-100 m-0 p-0 w-100 d-none">
      {% include 'mobile-nav.html' %}
    </div>
  </div>
  <script type="text/javascript" src="{% static 'js/jquery-3.5.1.js' %}"></script>
  <!-- <script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/*.js' %}"></script> -->
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/confirmation_dialog.html
<div class="d-none dialog_confirm d-flex justify-content-center align-items-center h-100 w-100">
    <div class="card text-center font-sm-md pb-2">
        <div class="card-header bg-primary text-light">
          SC : Demande de confirmation
        </div>
        <div class="card-body">
          <h5 class="card-title "></h5>
          <p class="card-text">Voulez-vous continuer ?</p>
        </div>
        <div class="d-flex justify-content-around">
            <a href="#" class="btn btn-primary">Annuler</a>
            <a href="#" class="btn btn-danger">Continuer</a>
        </div>
      </div>
</div>

templates/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div id="contact-page" class="row bg-dark p-2 pt-5 body-page-content container-fluid w-100">
    <div class="col-12 col-md-6 text-light text-right">
        <h1 class="text-right text-info">Contactez-nous</h1>
        <p class="text-right">Notre équipe est là ! prête à vous répondre</p>
                
        <p class="mt-4">
            <img src="{% static 'node_modules/bootstrap-icons/icons/mailbox.svg' %}" width="55" height="55"  alt="mail-icon" class="mt-2"> <br>
            Envoyez-nous un mail <br>
            <a href="mailto:spectrecorp@gmail.com" class="text-light">spectrecorp@gmail.com</a>
        </p>

        <p class="mt-4">
            <img src="{% static 'node_modules/bootstrap-icons/icons/telephone.svg' %}" width="55" height="55" alt="Contactez-nous"> <br>
            <a href="tel:06-586-95-05" class="text-light text-bolder">Appelez-nous au 06-586-95-05</a>
        </p>
    </div>
    <div class="col-12 col-md-6">
        <form>
            <div class="form-group ">
              <input type="text" class="form-control bg-dark rounded-0" placeholder="Entrez votre nom" required>
            </div>
            <div class="form-group mt-3">
              <input type="text" class="form-control bg-dark rounded-0" placeholder="Entrez votre email" required>
            </div>
            <div class="form-group mt-3">
                <textarea name="message" id="" rows="5"  class="form-control bg-dark rounded-0 text-light" required>Message
                
                </textarea>
            </div>
            <div class="form-group mt-3">
                <input type="submit" class="form-control text-light bg-dark rounded-0" value="Soumettre">
            </div>
            <div class="form-group mt-3 p-3 border bg-info">
            </div>
          </form>
    </div>
</div>
{% endblock %}

templates/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/base.css' %}">

templates/icons.html
{% load static %}
<div>
    <a href="{% url 'communication:box_msg' %}"><img src="{% static 'images/icons/chat.png' %}" alt=""></a>
    <span class="number"> {% if total_message_count %} {{ total_message_count }} {% endif %}</span>
</div>
<div>
    <a href="{% url 'communication:notifications' %}"><img src="{% static 'images/icons/notif.png' %}" alt=""></a>
    <span class="number">{% if notif_count >= 1%} {{ notif_count }} {% endif %}</span>
</div>
<div>
    <a href="{% url 'store:favourite' %}"><img src="{% static 'images/icons/heart.png' %}" alt=""></a>
</div>
<!--bip song for notif and message-->


<div>
    <div>
        <div class="img-user">
            <img
                {% if user.profil.avatar.url != "" %} 
                    src="{{ user.profil.avatar.url }}"
                {% else %}
                    src="{% static 'images/icons/stand.png' %}"
                {% endif %}
                    alt="" class="img_user"
            >
        </div>
    </div>
    <div class="profil-menu" style="display: none; z-index: 40;">
        <div>
            <ul>
                <a href=""><li>Mes paramètres</li></a>
                <a href="{% url 'user:profil' %}"><li>Mon profil</li></a>
                <a href="{% url 'user:logout' %}"><li>Déconnexion</li></a>
            </ul>
        </div>
    </div>
</div>

templates/mobile-nav.html
{% load static %}
<div class="d-flex flex-column">
    <div class="d-flex justify-content-end p-2"> <img src="{% static 'node_modules/bootstrap-icons/icons/x-octagon-fill.svg' %}" 
        alt="Bootstrap" width="32" height="32" class="pointer cancel-menu-btn"></div>
    {% if request.user.is_authenticated %}
        <a href="{% url 'user:logout' %}" class="btn btn-outline-dark mb-2">Se déconnecter</a>
    {% else %}
        <a href="{% url 'user:auto_login' %}" class="btn btn-outline-dark mb-2">se connecter | s'inscrire</a>
    {% endif %}
    <a href="{% url 'store:create_article' %}" class="btn btn-primary mb-2">Poster un article </a>
    <a href="{% url 'work_step' %}" class="text-center text-decoration-none">Comment ça marche ?</a>
</div>
<div class="">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link" id="v-pills-home-tab" data-toggle="pill" href="{% url 'store:home' %}" role="tab" aria-controls="v-pills-home" aria-selected="true">Acceuil</a>
        <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="{% url 'store:my_articles' %}" role="tab" aria-controls="v-pills-settings" aria-selected="false">Mes articles</a>
        <a class="nav-link dashboard-link" id="v-pills-settings-tab" data-toggle="pill" href="{% url 'dashboard:orders' %}envoyees" role="tab" aria-controls="v-pills-settings" aria-selected="false">Tableau de bord</a>
        <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="{% url 'store:favourite' %}" role="tab" aria-controls="v-pills-settings" aria-selected="false">Favoris</a>
        <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="{% url 'communication:notifications' %}" role="tab" aria-controls="v-pills-settings" aria-selected="false">Notifications
            {% if notif_count > 0 %}<span class="badge bg-primary">{{ notif_count }}</span></a>{% endif %}
        </a>
        <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="{% url 'about' %}" role="tab" aria-controls="v-pills-profile" aria-selected="false">A propos de nous</a>
        <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="{% url 'contact' %}" role="tab" aria-controls="v-pills-messages" aria-selected="false">Contact</a>
        <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="{% url 'user:profil' %}" role="tab" aria-controls="v-pills-messages" aria-selected="false">Paramètres</a>
    </div>
</div>

templates/no_connection.html
<!DOCTYPE html>
<html lang="fr">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/no_connection.css' %}">
    <title>sc</title>
</head>
<body>
    <h1>Vendez ou achetez vos articles en ligne et en toute sécurité</h1>

    <img src="{% static 'images/icons/logo.png' %}"  width="140" height="140" alt="logo sc">

    <div>
        <p>SC semble ne pas être connecté à internet</p>
        <p><a href="{% url 'store:home' %}"><button>ACTUALISER</button></a></p>
        <p>Verifiez votre connection Internet</p>
    </div>
</body>
</html>